"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LIST_CITY_AR = exports.LIST_CITY_EN = void 0;
exports.LIST_CITY_EN = [
    { value: null, label: "All" },
    { value: "alexandria", label: "Alexandria" },
    { value: "aswan", label: "Aswan" },
    { value: "asyut", label: "Asyut" },
    { value: "beni_suef", label: "Beni Suef" },
    { value: "cairo", label: "Cairo" },
    { value: "damietta", label: "Damietta" },
    { value: "damanhur", label: "Damanhur" },
    { value: "faiyum", label: "Faiyum" },
    { value: "giza", label: "Giza" },
    { value: "hurghada", label: "Hurghada" },
    { value: "ismailia", label: "Ismailia" },
    { value: "kafr_el_sheikh", label: "Kafr El Sheikh" },
    { value: "luxor", label: "Luxor" },
    { value: "mansoura", label: "Mansoura" },
    { value: "minya", label: "Minya" },
    { value: "port_said", label: "Port Said" },
    { value: "qasr_al_farafra", label: "Qasr Al Farafra" },
    { value: "qena", label: "Qena" },
    { value: "sharm_el_sheikh", label: "Sharm El Sheikh" },
    { value: "sohag", label: "Sohag" },
    { value: "suez", label: "Suez" },
    { value: "tanta", label: "Tanta" },
    { value: "zagazig", label: "Zagazig" },
];
exports.LIST_CITY_AR = [
    { value: null, label: "الكل" },
    { value: "alexandria", label: "الإسكندرية" },
    { value: "aswan", label: "أسوان" },
    { value: "asyut", label: "أسيوط" },
    { value: "beni_suef", label: "بني سويف" },
    { value: "cairo", label: "القاهرة" },
    { value: "damietta", label: "دمياط" },
    { value: "damanhur", label: "دمنهور" },
    { value: "faiyum", label: "الفيوم" },
    { value: "giza", label: "الجيزة" },
    { value: "hurghada", label: "الغردقة" },
    { value: "ismailia", label: "الإسماعيلية" },
    { value: "kafr_el_sheikh", label: "كفر الشيخ" },
    { value: "luxor", label: "الأقصر" },
    { value: "mansoura", label: "المنصورة" },
    { value: "minya", label: "المنيا" },
    { value: "port_said", label: "بورسعيد" },
    { value: "qasr_al_farafra", label: "قصر الفرافرة" },
    { value: "qena", label: "قنا" },
    { value: "sharm_el_sheikh", label: "شرم الشيخ" },
    { value: "sohag", label: "سوهاج" },
    { value: "suez", label: "السويس" },
    { value: "tanta", label: "طنطا" },
    { value: "zagazig", label: "الزقازيق" },
];
//# sourceMappingURL=city.js.map